export const songMoodsOptions = [
  "Acerbic",
  "Aggressive",
  "Agreeable",
  "Airy",
  "Ambitious",
  "Amiable/Good-Natured",
  "Angry",
  "Angst-Ridden",
  "Anguished/Distraught",
  "Angular",
  "Animated",
  "Anthemic",
  "Apocalyptic",
  "Arid",
  "Athletic",
  "Atmospheric",
  "Austere",
  "Autumnal",
  "Belligerent",
  "Benevolent",
  "Bitter",
  "Bittersweet",
  "Bleak",
  "Boisterous",
  "Bombastic",
  "Bouncy",
  "Brash",
  "Brassy",
  "Bravado",
  "Bright",
  "Brittle",
  "Brooding",
  "Calm/Peaceful",
  "Campy",
  "Capricious",
  "Carefree",
  "Cartoonish",
  "Cathartic",
  "Celebratory",
  "Cerebral",
  "Cheerful",
  "Child-like",
  "Circular",
  "Clinical",
  "Cold",
  "Comic",
  "Complex",
  "Concise",
  "Confessional",
  "Confident",
  "Confrontational",
  "Cosmopolitan",
  "Crunchy",
  "Cute",
  "Cynical/Sarcastic",
  "Dark",
  "Declamatory",
  "Defiant",
  "Delicate",
  "Demonic",
  "Desperate",
  "Detached",
  "Devotional",
  "Difficult",
  "Dignified/Noble",
  "Dissonant",
  "Dramatic",
  "Dreamy",
  "Driving",
  "Druggy",
  "Earnest",
  "Earthy",
  "Ebullient",
  "Eccentric",
  "Ecstatic",
  "Eerie",
  "Effervescent",
  "Elaborate",
  "Elegant",
  "Elegiac",
  "Energetic",
  "Enigmatic",
  "Epic",
  "Erotic",
  "Ethereal",
  "Euphoric",
  "Exciting",
  "Exotic",
  "Exploratory",
  "Explosive",
  "Extroverted",
  "Exuberant",
  "Fantastic/Fantasy-like",
  "Feral",
  "Feverish",
  "Fierce",
  "Fiery",
  "Flashy",
  "Flowing",
  "Fractured",
  "Freewheeling",
  "Fun",
  "Funereal",
  "Gentle",
  "Giddy",
  "Gleeful",
  "Gloomy",
  "Graceful",
  "Greasy",
  "Grim",
  "Gritty",
  "Gutsy",
  "Happy",
  "Harsh",
  "Heavy",
  "Hedonistic",
  "Heroic",
  "Hostile",
  "Humorous",
  "Hungry",
  "Hymn-like",
  "Hyper",
  "Hypnotic",
  "Improvisatory",
  "Indulgent",
  "Innocent",
  "Insular",
  "Intense",
  "Intimate",
  "Introspective",
  "Ironic",
  "Irreverent",
  "Jovial",
  "Joyous",
  "Kinetic",
  "Knotty",
  "Laid-Back/Mellow",
  "Languid",
  "Lazy",
  "Light",
  "Literate",
  "Lively",
  "Lonely",
  "Loose",
  "Lush",
  "Lyrical",
  "Macabre",
  "Magical",
  "Majestic",
  "Malevolent",
  "Manic",
  "Marching",
  "Martial",
  "Meandering",
  "Mechanical",
  "Meditative",
  "Melancholy",
  "Melodic",
  "Menacing",
  "Messy",
  "Mighty",
  "Monastic",
  "Monumental",
  "Motoric",
  "Mysterious",
  "Mystical",
  "Naive",
  "Narcotic",
  "Narrative",
  "Negative",
  "Nervous/Jittery",
  "Nihilistic",
  "Nocturnal",
  "Nostalgic",
  "Ominous",
  "Optimistic",
  "Opulent",
  "Organic",
  "Ornate",
  "Outraged",
  "Outrageous",
  "Paranoid",
  "Passionate",
  "Pastoral",
  "Patriotic",
  "Perky",
  "Philosophical",
  "Plain",
  "Plaintive",
  "Playful",
  "Poetic",
  "Poignant",
  "Positive",
  "Powerful",
  "Precious",
  "Provocative",
  "Pulsing",
  "Pure",
  "Quaint",
  "Quirky",
  "Radiant",
  "Rambunctious",
  "Ramshackle",
  "Raucous",
  "Reassuring/Consoling",
  "Rebellious",
  "Reckless",
  "Refined",
  "Reflective",
  "Regretful",
  "Relaxed",
  "Reserved",
  "Resolute",
  "Restrained",
  "Reverent",
  "Rhapsodic",
  "Rollicking",
  "Romantic",
  "Rousing",
  "Rowdy",
  "Rustic",
  "Sacred",
  "Sad",
  "Sarcastic",
  "Sardonic",
  "Satirical",
  "Savage",
  "Scary",
  "Scattered",
  "Searching",
  "Seductive",
  "Self-Conscious",
  "Sensual",
  "Sentimental",
  "Serious",
  "Severe",
  "Sexual",
  "Sexy",
  "Shimmering",
  "Silly",
  "Sleazy",
  "Slick",
  "Smooth",
  "Snide",
  "Soft/Quiet",
  "Somber",
  "Soothing",
  "Sophisticated",
  "Spacey",
  "Spacious",
  "Sparkling",
  "Sparse",
  "Spicy",
  "Spiritual",
  "Spontaneous",
  "Spooky",
  "Sprawling",
  "Sprightly",
  "Springlike",
  "Stately",
  "Street-Smart",
  "Striding",
  "Strong",
  "Stylish",
  "Suffocating",
  "Sugary",
  "Summery",
  "Sunny",
  "Suspenseful",
  "Swaggering",
  "Sweet",
  "Swinging",
  "Technical",
  "Tender",
  "Tense/Anxious",
  "Theatrical",
  "Thoughtful",
  "Threatening",
  "Thrilling",
  "Tight",
  "Tough",
  "Tragic",
  "Transparent/Translucent",
  "Trashy",
  "Trippy",
  "Triumphant",
  "Turbulent",
  "Uncompromising",
  "Understated",
  "Unsettling",
  "Uplifting",
  "Urgent",
  "Virile",
  "Visceral",
  "Volatile",
  "Vulgar",
  "Vulnerable",
  "Warm",
  "Weary",
  "Whimsical",
  "Wintry",
  "Wistful",
  "Witty",
  "Wry",
  "Yearning",
];
export const genrePrimaryOptions = [
  "Alternative",
  "Anime",
  "Blues",
  "Children's Music",
  "Classical",
  "Comedy",
  "Commercial",
  "Country",
  "Dance (EDM)",
  "Disney",
  "Easy Listening",
  "Electronic",
  "Enka",
  "French Pop",
  "Folk Music",
  "German Folk",
  "German Pop",
  "Fitness & Workout",
  "Hip-Hop/Rap",
  "Holiday",
  "Indie Pop",
  "Industrial",
  "Inspirational - Christian & Gospel",
  "Instrumental",
  "J-Pop",
  "Jazz",
  "K-Pop",
  "Karaoke",
  "Kayokyoku",
  "Latin",
  "Metal",
  "New Age",
  "Opera",
  "Pop",
  "R&B/Soul",
  "Reggae",
  "Rock",
  "Singer/Songwriter",
  "Soundtrack",
  "Spoken Word",
  "Tex-Mex / Tejano",
  "Vocal",
  "World",
];

export const genreSecondaryOptions = [
  "Art Punk",
  "Alternative Rock",
  "Britpunk",
  "College Rock",
  "Crossover Thrash",
  "Crust Punk (thx Haug)",
  "Emo",
  "Experimental Rock",
  "Folk Punk",
  "Goth / Gothic Rock",
  "Grunge",
  "Hardcore Punk",
  "Hard Rock",
  "Indie Rock",
  "Lo-fi",
  "Musique Concrète",
  "New Wave",
  "Progressive Rock",
  "Punk",
  "Shoegaze",
  "Steampunk",
  "Acoustic Blues",
  "African Blues",
  "Blues Rock",
  "Blues Shouter",
  "British Blues",
  "Canadian Blues",
  "Chicago Blues",
  "Classic Blues",
  "Classic Female Blues",
  "Contemporary Blues",
  "Contemporary R&B",
  "Country Blues",
  "Dark Blues",
  "Delta Blues",
  "Detroit Blues",
  "Doom Blues",
  "Electric Blues",
  "Folk Blues",
  "Gospel Blues",
  "Harmonica Blues",
  "Hill Country Blues",
  "Hokum Blues",
  "Jazz Blues",
  "Jump Blues",
  "Kansas City Blues",
  "Louisiana Blues",
  "Memphis Blues",
  "Modern Blues",
  "New Orlean Blues",
  "NY Blues",
  "Piano Blues",
  "Piedmont Blues",
  "Punk Blues",
  "Ragtime Blues",
  "Rhythm Blues",
  "Soul Blues",
  "St. Louis Blues",
  "Soul Blues",
  "Swamp Blues",
  "Texas Blues",
  "Urban Blues",
  "Vandeville",
  "West Coast Blues",
  "Zydeco",
  "Lullabies",
  "Sing-Along",
  "Stories",
  "Avant-Garde",
  "Ballet",
  "Baroque",
  "Cantata",
  "Chamber Music",
  "String Quartet",
  "Chant",
  "Choral",
  "Classical Crossover",
  "Concerto",
  "Concerto Grosso",
  "Contemporary Classical",
  "Early Music",
  "Expressionist",
  "High Classical",
  "Impressionist",
  "Mass Requiem",
  "Medieval",
  "Minimalism",
  "Modern Composition",
  "Modern Classical",
  "Opera",
  "Oratorio",
  "Orchestral",
  "Organum",
  "Renaissance",
  "Romantic (early period)",
  "Romantic (later period)",
  "Sonata",
  "Symphonic",
  "Symphony",
  "Twelve-tone",
  "Wedding Music",
  "Novelty",
  "Parody Music",
  "Stand-up Comedy",
  "Vaudeville",
  "Jingles",
  "TV Themes",
  "Alternative Country",
  "Americana",
  "Australian Country",
  "Bakersfield Sound",
  "Bluegrass",
  "Blues Country",
  "Cajun Fiddle Tunes",
  "Christian Country",
  "Classic Country",
  "Close Harmony",
  "Contemporary Bluegrass",
  "Contemporary Country",
  "Country Gospel",
  "Country Pop",
  "Country Rap",
  "Country Rock",
  "Country Soul",
  "Cowboy / Western",
  "Cowpunk",
  "Dansband",
  "Honky Tonk",
  "Franco-Country",
  "Gulf and Western",
  "Hellbilly Music",
  "Honky Tonk",
  "Instrumental Country",
  "Lubbock Sound",
  "Nashville Sound",
  "Neotraditional Country",
  "Outlaw Country",
  "Progressive",
  "Psychobilly / Punkabilly",
  "Red Dirt",
  "Sertanejo",
  "Texas County",
  "Traditional Bluegrass",
  "Traditional Country",
  "Truck-Driving Country",
  "Urban Cowboy",
  "Western Swing",
  "Zydeco",
  "Club / Club Dance",
  "Breakcore",
  "Breakbeat",
  "Breakstep",
  "Brostep",
  "Chillstep",
  "Deep House",
  "Drum’n’bass",
  "Dubstep",
  "Electro House",
  "Electroswing",
  "Exercise",
  "Future Garage",
  "Garage",
  "Glitch Hop",
  "Glitch Pop",
  "Grime",
  "Hardcore",
  "Hard Dance",
  "Hi-NRG / Eurodance",
  "Horrorcore",
  "House",
  "Jackin House",
  "Jungle",
  "Liquid Dub",
  "Progressive",
  "Regstep",
  "Speedcore",
  "Techno",
  "Trance",
  "Trap",
  "Background",
  "Bop",
  "Elevator",
  "Furniture",
  "Lounge",
  "Middle of the Road",
  "Swing",
  "2-Step",
  "8bit",
  "Ambient",
  "Asian Underground",
  "Bassline",
  "Chillwave",
  "Chiptune",
  "Crunk",
  "Downtempo",
  "Drum & Bass",
  "Electro",
  "Electro-swing",
  "Electroacoustic",
  "Electronica",
  "Electronic Rock",
  "Eurodance",
  "Hardstyle",
  "Hi-Nrg",
  "IDM/Experimental",
  "Industrial",
  "Trip Hop",
  "Vaporwave",
  "UK Garage",
  "American Folk Revival",
  "Anti-Folk",
  "British Folk Revival",
  "Contemporary Folk",
  "Filk Music",
  "Freak Folk",
  "Indie Folk",
  "Industrial Folk",
  "Neofolk",
  "Progressive Folk",
  "Psychedelic Folk",
  "Sung Poetry",
  "Techno-Folk",
  "Alternative Rap",
  "Avant-Garde",
  "Bounce",
  "Chap Hop",
  "Christian Hip Hop",
  "Conscious Hip Hop",
  "Country-Rap",
  "Grunk",
  "Crunkcore",
  "Cumbia Rap",
  "Dirty South",
  "East Coast",
  "Freestyle Rap",
  "G-Funk",
  "Gangsta Rap",
  "Golden Age",
  "Grime",
  "Hardcore Rap",
  "Hip-Hop",
  "Hip Pop",
  "Horrorcore",
  "Hyphy",
  "Industrial Hip Hop",
  "Instrumental Hip Hop",
  "Jazz Rap",
  "Latin Rap",
  "Low Bap",
  "Lyrical Hip Hop",
  "Merenrap",
  "Midwest Hip Hop",
  "Motswako",
  "Nerdcore",
  "New Jack Swing",
  "New School Hip Hop",
  "Old School Rap",
  "Rap",
  "Trap",
  "Turntablism",
  "Underground Rap",
  "West Coast Rap",
  "Chanukah",
  "Christmas",
  "Christmas: Children’s",
  "Christmas: Classic",
  "Christmas: Classical",
  "Christmas: Comedy",
  "Christmas: Jazz",
  "Christmas: Modern",
  "Christmas: Pop",
  "Christmas: R&B",
  "Christmas: Religious",
  "Christmas: Rock",
  "Easter",
  "Halloween",
  "Holiday: Other",
  "Thanksgiving",
  "Aggrotech",
  "Coldwave",
  "Cybergrind",
  "Dark Electro",
  "Death Industrial",
  "Electro-Industrial",
  "Electronic Body Music",
  "Industrial Metal",
  "Industrial Rock",
  "Noise",
  "Witch House",
  "CCM",
  "Christian Metal",
  "Christian Pop",
  "Christian Rap",
  "Christian Rock",
  "Classic Christian",
  "Contemporary Gospel",
  "Gospel",
  "Christian & Gospel",
  "Praise & Worship",
  "Qawwali",
  "Southern Gospel",
  "Traditional Gospel",
  "March (Marching Band)",
  "J-Rock",
  "J-Synth",
  "J-Ska",
  "J-Punk",
  "Acid Jazz",
  "Afro-Cuban Jazz",
  "Avant-Garde Jazz",
  "Bebop",
  "Big Band",
  "Blue Note",
  "British Dance Band (Jazz)",
  "Cape Jazz",
  "Chamber Jazz",
  "Contemporary Jazz",
  "Continental Jazz",
  "Cool Jazz",
  "Crossover Jazz",
  "Dark Jazz",
  "Dixieland",
  "Early Jazz",
  "Electro Swing (Jazz)",
  "Ethio-jazz",
  "Ethno-Jazz",
  "European Free Jazz",
  "Free Funk (Avant-Garde / Funk Jazz)",
  "Free Jazz",
  "Fusion",
  "Gypsy Jazz",
  "Hard Bop",
  "Indo Jazz",
  "Jazz Blues",
  "Jazz-Funk (see Free Funk)",
  "Jazz-Fusion",
  "Jazz Rap",
  "Jazz Rock",
  "Kansas City Jazz",
  "Latin Jazz",
  "M-Base Jazz",
  "Mainstream Jazz",
  "Modal Jazz",
  "Neo-Bop",
  "Neo-Swing",
  "Nu Jazz",
  "Orchestral Jazz",
  "Post-Bop",
  "Punk Jazz",
  "Ragtime",
  "Ska Jazz",
  "Skiffle (also Folk)",
  "Smooth Jazz",
  "Soul Jazz",
  "Swing Jazz",
  "Straight-Ahead Jazz",
  "Trad Jazz",
  "Third Stream",
  "Jazz-Funk",
  "Free Jazz",
  "West Coast Jazz",
  "Alternativo & Rock Latino",
  "Argentine Tango",
  "Bachata",
  "Baithak Gana",
  "Baladas y Boleros",
  "Bolero",
  "Bossa Nova",
  "Brazilian",
  "Chicha",
  "Criolla",
  "Contemporary Latin",
  "Cumbia",
  "Flamenco / Spanish Flamenco",
  "Huayno",
  "Joropo",
  "Latin Jazz",
  "Mambo (Cuba)",
  "Mariachi",
  "Merengue Típico",
  "Nuevo Flamenco",
  "Pop Latino",
  "Portuguese Fado",
  "Punta",
  "Punta Rock",
  "Ranchera",
  "Raíces",
  "Raison",
  "Reggaeton y Hip-Hop",
  "Regional Mexicano",
  "Salsa y Tropical",
  "Soca",
  "Son",
  "Tejano",
  "Timba",
  "Twoubadou",
  "Vallenato",
  "Zouk",
  "Heavy Metal",
  "Speed Metal",
  "Thrash Metal",
  "Power Metal",
  "Death Metal",
  "Black Metal",
  "Pagan Metal",
  "Viking Metal",
  "Folk Metal",
  "Symphonic Metal",
  "Gothic Metal",
  "Glam Metal",
  "Hair Metal",
  "Doom Metal",
  "Groove Metal",
  "Industrial Metal",
  "Modern Metal",
  "Neoclassical Metal",
  "New Wave Of British Heavy Metal",
  "Post Metal",
  "Progressive Metal",
  "Avantgarde Metal",
  "Sludge",
  "Djent",
  "Drone",
  "Kawaii Metal",
  "Pirate Metal",
  "Nu Metal",
  "Neue Deutsche Härte",
  "Math Metal",
  "Crossover",
  "Grindcore",
  "Hardcore",
  "Metalcore",
  "Deathcore",
  "Post Hardcore",
  "Mathcore",
  "Environmental",
  "Healing",
  "Meditation",
  "Nature",
  "Relaxation",
  "Trave",
  "Adult Contemporary",
  "Arab Pop",
  "Baroque",
  "Britpop",
  "Bubblegum Pop",
  "Chamber Pop",
  "Chanson",
  "Christian Pop",
  "Classical Crossover",
  "Europop",
  "Dance Pop",
  "Dream Pop",
  "Electro Pop",
  "Iranian Pop",
  "Jangle Pop",
  "Latin Ballad",
  "Levenslied",
  "Louisiana Swamp Pop",
  "Mexican Pop",
  "Motorpop",
  "New Romanticism",
  "Orchestral Pop",
  "Pop Rap",
  "Popera",
  "Pop/Rock",
  "Pop Punk",
  "Power Pop",
  "Psychedelic Pop",
  "Schlager",
  "Soft Rock",
  "Sophisti-Pop",
  "Space Age Pop",
  "Sunshine Pop",
  "Surf Pop",
  "Synthpop",
  "Teen Pop",
  "Traditional Pop Music",
  "Turkish Pop",
  "Vispop",
  "Wonky Pop",
  "Post-Disco",
  "(Carolina) Beach Music",
  "Contemporary R&B",
  "Disco",
  "Doo Wop",
  "Funk",
  "Modern Soul",
  "Motown",
  "Neo-Soul",
  "Northern Soul",
  "Psychedelic Soul",
  "Quiet Storm",
  "Soul",
  "Soul Blues",
  "Southern Soul",
  "2-Tone",
  "Dub",
  "Roots Reggae",
  "Reggae Fusion",
  "Reggae en Español",
  "Lovers Rock",
  "Raggamuffin",
  "Ska",
  "Reggae Dancehall",
  "Acid Rock",
  "Adult-Oriented Rock",
  "Afro Punk",
  "Adult Alternative",
  "Alternative Rock",
  "American Traditional Rock",
  "Anatolian Rock",
  "Arena Rock",
  "Art Rock",
  "Blues-Rock",
  "British Invasion",
  "Cock Rock",
  "Death Metal / Black Metal",
  "Doom Metal",
  "Glam Rock",
  "Gothic Metal",
  "Grind Core",
  "Hair Metal",
  "Hard Rock",
  "Math Metal",
  "Math Rock",
  "Metal",
  "Metal Core",
  "Noise Rock",
  "Jam Bands",
  "Post Punk",
  "Post Rock",
  "Prog-Rock/Art Rock",
  "Progressive Metal",
  "Psychedelic",
  "Rock & Roll",
  "Rockabilly",
  "Roots Rock",
  "Singer/Songwriter",
  "Southern Rock",
  "Spazzcore",
  "Stoner Metal (duuuude)",
  "Surf",
  "Technical Death Metal",
  "Tex-Mex",
  "Thrash Metal",
  "Time Lord Rock (Trock)",
  "Trip-hop",
  "Yacht Rock (soft rock)",
  "Alternative Folk",
  "Contemporary Folk",
  "Contemporary Singer/Songwriter",
  "Indie Folk",
  "Folk-Rock",
  "Love Song (Chanson)",
  "New Acoustic",
  "Traditional Folk",
  "Foreign Cinema",
  "Movie Soundtrack",
  "Musicals",
  "Original Score",
  "Soundtrack",
  "TV Soundtrack",
  "Chicano",
  "Classic",
  "Conjunto",
  "Conjunto Progressive",
  "New Mex",
  "Tex-Mex",
  "A cappella",
  "Barbershop",
  "Cantique (sacred vocal)",
  "Doo-wop",
  "Gregorian Chant",
  "Standards",
  "Traditional Pop",
  "Vocal Jazz",
  "Vocal Pop",
  "Yodel",
  "Africa",
  "Asia",
  "Australia",
  "Cajun",
  "Calypso",
  "Caribbean",
  "Carnatic (Karnataka Sanghetha)",
  "Celtic",
  "Celtic Folk",
  "Contemporary Celtic",
  "Coupé-décalé – Congo",
  "Dangdut",
  "Drinking Songs",
  "Drone",
  "Fado",
  "Laiko",
  "Entechno",
  "Rebetika",
  "Schlager",
  "France",
  "Hawaii",
  "Japan",
  "Klezmer",
  "Mbalax – Senegal",
  "Middle East",
  "North America",
  "Ode",
  "Piphat – Thailand",
  "Polka",
  "Soca",
  "South Africa",
  "South America",
  "South / Southeast Asia",
  "Traditional Celtic",
  "Worldbeat",
  "Zydeco",
];
export const subGenreOptions = [
  "Progressive Bluegrass",
  "Reactionary Bluegrass",

  "4-Beat",
  "Acid Breaks",
  "Baltimore Club",
  "Big Beat",
  "Breakbeat Hardcore",
  "Broken Beat",
  "Florida Breaks",
  "Nu Skool Breaks",

  "Bouncy House",
  "Bouncy Techno",
  "Breakcore",
  "Digital Hardcore",
  "Doomcore",
  "Dubstyle",
  "Gabber",
  "Happy Hardcore",
  "Hardstyle",
  "Jumpstyle",
  "Makina",
  "Speedcore",
  "Terrorcore",
  "Uk Hardcore",

  "Acid House",
  "Chicago House",
  "Deep House",
  "Diva House",
  "Dutch House",
  "Electro House",
  "Freestyle House",
  "French House",
  "Funky House",
  "Ghetto House",
  "Hardbag",
  "Hip House",
  "Italo House",
  "Latin House",
  "Minimal House",
  "Progressive House",
  "Rave Music",
  "Swing House",
  "Tech House",
  "Tribal House",
  "Tropical House",
  "UK Hard House",
  "US Garage",
  "Vocal House",

  "Progressive House / Trance",
  "Disco House",
  "Dream House",
  "Space House",
  "Japanese House",
  "Bounce / Scouse House",
  "Progressive Breaks",
  "Progressive Drum & Bass",
  "Progressive Techno",

  "Acid Techno",
  "Detroit Techno",
  "Free Tekno",
  "Ghettotech",
  "Minimal",
  "Nortec",
  "Schranz",
  "Techno-Dnb",
  "Technopop",
  "Tecno Brega",
  "Toytown Techno",

  "Acid Trance",
  "Acid-House",
  "Classic Trance",
  "Dark Psy",
  "Deep House",
  "Dream Trance",
  "Goa Trance",
  "Dark Psytrance",
  "Full on",
  "Psybreaks",
  "Psyprog",
  "Suomisaundi",
  "Hard Trance",
  "Prog. Trance",
  "Psy-Trance",
  "Minimal Techno",
  "Tech House",
  "Tech Trance",
  "Uplifting Trance",
  "Orchestral Uplifting",
  "Vocal Trance",

  "Ambient Dub",
  "Ambient House",
  "Ambient Techno",
  "Dark Ambient",
  "Drone Music",
  "Illbient",
  "Isolationism",
  "Lowercase",

  "Bitpop",
  "Game Boy",
  "Nintendocore",
  "Video Game Music",
  "Yorkshire Bleeps and Bass",

  "Acid Jazz",
  "Balearic Beat",
  "Chill Out",
  "Dub Music",
  "Dubtronica",
  "Ethnic Electronica",
  "Moombahton",
  "Nu Jazz",
  "Trip Hop",

  "Darkcore",
  "Darkstep",
  "Drumfunk",
  "Drumstep",
  "Hardstep",
  "Intelligent Drum and Bass",
  "Jump-Up",
  "Liquid Funk",
  "Neurofunk",
  "Oldschool Jungle:",
  "Darkside Jungle",
  "Ragga Jungle",
  "Raggacore",
  "Sambass",
  "Techstep",

  "Crunk",
  "Electro Backbeat",
  "Electro-Grime",
  "Electropop",

  "Acousmatic Music",
  "Computer Music",
  "Electroacoustic Improvisation",
  "Field Recording",
  "Live Coding",
  "Live Electronics",
  "Soundscape Composition",
  "Tape Music",

  "Berlin School",
  "Chillwave",
  "Electronic Art Music",
  "Electronic Dance Music",
  "Folktronica",
  "Freestyle Music",
  "Glitch",
  "Idm",
  "Laptronica",
  "Skweee",
  "Sound Art",
  "Synthcore",

  "Alternative Dance",
  "Baggy",
  "Madchester",
  "Dance-Punk",
  "Dance-Rock",
  "Dark Wave",
  "Electroclash",
  "Electronicore",
  "Electropunk",
  "Ethereal Wave",
  "Indietronica",
  "New Rave",
  "Space Rock",
  "Synthpop",
  "Synthpunk",

  "Bubblegum Dance",
  "Italo Dance",
  "Turbofolk",

  "Eurobeat",
  "Hard Nrg",
  "New Beat",

  "Hyponagogic",
  "Vektroid",
  "Mallsoft",
  "Vaportrap",
  "Vaporhop",
  "Protovapor",

  "2-Step",
  "4×4",
  "Bassline",
  "Grime",
  "Speed Garage",

  "Brick City Club",
  "Hardcore Hip Hop",
  "Mafioso Rap",
  "New Jersey Hip Hop",

  "Chicago Hip Hop",
  "Detroit Hip Hop",
  "Horrorcore",
  "St. Louis Hip Hop",
  "Twin Cities Hip Hop",

  "Futurepop",

  "Japanoise",
  "Power Electronics",
  "Power Noise",

  "Axé",
  "Bossa Nova",
  "Brazilian Rock",
  "Brega",
  "Choro",
  "Forró",
  "Frevo",
  "Funk Carioca",
  "Lambada",
  "Maracatu",
  "Música Popular Brasileira",
  "Música Sertaneja",
  "Pagode",
  "Samba",
  "Samba Rock",
  "Tecnobrega",
  "Tropicalia",
  "Zouk-Lambada",

  "Austropop",
  "Balkan Pop",
  "French Pop",
  "Latin Pop",
  "Laïkó",
  "Nederpop",
  "Russian Pop",

  "Boogie",
  "Dance-pop",

  "Spanish Reggae",
  "Reggae 110",
  "Reggae Bultrón",
  "Romantic Flow",

  "Ragga",
  "Dancehall",
  "2 Tone",
  "Dub",
  "Rocksteady",
  "African Heavy Metal",
  "African Hip Hop",
  "Afro-Beat",
  "Afro-House",
  "Afro-Pop",
  "Apala (or akpala)",
  "Benga",
  "Bikutsi",
  "Bongo Flava",
  "Cape Jazz",
  "Chimurenga",
  "Coupé-Décalé",
  "Fuji Music",
  "Genge",
  "Gnawa (hypnotic trance)",
  "Highlife",
  "Hiplife",
  "Isicathamiya",
  "Jit",
  "Jùjú",
  "Kapuka",
  "Kizomba",
  "Kuduro",
  "Kwaito",
  "Kwela",
  "Lingala (Rumba Lingala / Congolese Rumba)",
  "Makossa",
  "Maloya",
  "Marrabenta",
  "Mbalax",
  "Mbaqanga",
  "Mbube",
  "Morna",
  "Museve",
  "Negro Spiritual",
  "Palm-Wine",
  "Raï",
  "Sakara",
  "Sega",
  "Seggae",
  "Semba",
  "Soukous",
  "Taarab",
  "Zouglou",
  "Anison",
  "Baithak Gana",
  "C-Pop",
  "CityPop",
  "Cantopop",
  "Enka",
  "Hong Kong English Pop",
  "Fann At-Tanbura",
  "Fijiri",
  "J-Pop",
  "Japanese Pop",
  "K-Pop",
  "Khaliji",
  "Kayōkyoku",
  "Korean Pop",
  "Liwa",
  "Mandopop",
  "Onkyokei",
  "Taiwanese Pop",
  "T-Pop (Thai pop)",
  "Sawt",
  "Chutney",
  "Chutney Soca",
  "Compas",
  "Mambo",
  "Merengue",
  "Méringue",
  "Baila",
  "Bhangra",
  "Bhojpuri",
  "Dangdut",
  "Filmi",
  "Indian Pop",
  "Hindustani",
  "Indian Ghazal",
  "Lavani",
  "Luk Thung",
  "Luk Krung",
  "Manila Sound",
  "Morlam",
  "Pinoy Pop",
  "Pop Sunda",
  "Ragini",
  "Thai Pop",
];
